package com.denny.t5.handson.domain.model.entity;

import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.EMP_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.ENAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.MGR
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.HIRED_DATE
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Date hiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.SAL
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Integer sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.DEPT_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMP.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.EMP_ID
     *
     * @return the value of EMP.EMP_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.EMP_ID
     *
     * @param empId the value for EMP.EMP_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.ENAME
     *
     * @return the value of EMP.ENAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.ENAME
     *
     * @param ename the value for EMP.ENAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.JOB_ID
     *
     * @return the value of EMP.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.JOB_ID
     *
     * @param jobId the value for EMP.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.MGR
     *
     * @return the value of EMP.MGR
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.MGR
     *
     * @param mgr the value for EMP.MGR
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setMgr(String mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.HIRED_DATE
     *
     * @return the value of EMP.HIRED_DATE
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Date getHiredDate() {
        return hiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.HIRED_DATE
     *
     * @param hiredDate the value for EMP.HIRED_DATE
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setHiredDate(Date hiredDate) {
        this.hiredDate = hiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.SAL
     *
     * @return the value of EMP.SAL
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Integer getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.SAL
     *
     * @param sal the value for EMP.SAL
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setSal(Integer sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.DEPT_ID
     *
     * @return the value of EMP.DEPT_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.DEPT_ID
     *
     * @param deptId the value for EMP.DEPT_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.DEL_FLG
     *
     * @return the value of EMP.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.DEL_FLG
     *
     * @param delFlg the value for EMP.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.CREATED_AT
     *
     * @return the value of EMP.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.CREATED_AT
     *
     * @param createdAt the value for EMP.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP.UPDATED_AT
     *
     * @return the value of EMP.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP.UPDATED_AT
     *
     * @param updatedAt the value for EMP.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}