package com.denny.t5.handson.domain.model.entity;

import java.util.Date;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB.JNAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String jname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private String delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB.JOB_ID
     *
     * @return the value of JOB.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB.JOB_ID
     *
     * @param jobId the value for JOB.JOB_ID
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB.JNAME
     *
     * @return the value of JOB.JNAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB.JNAME
     *
     * @param jname the value for JOB.JNAME
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setJname(String jname) {
        this.jname = jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB.DEL_FLG
     *
     * @return the value of JOB.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB.DEL_FLG
     *
     * @param delFlg the value for JOB.DEL_FLG
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB.CREATED_AT
     *
     * @return the value of JOB.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB.CREATED_AT
     *
     * @param createdAt the value for JOB.CREATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB.UPDATED_AT
     *
     * @return the value of JOB.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB.UPDATED_AT
     *
     * @param updatedAt the value for JOB.UPDATED_AT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}