package com.denny.t5.handson.domain.mapper;

import java.util.List;

import com.denny.t5.handson.domain.model.entity.Dept;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int deleteByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    Dept selectByPrimaryKey(String deptId);

    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPT
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int updateByPrimaryKey(Dept record);
}