package com.denny.t5.handson.domain.mapper;

import com.denny.t5.handson.domain.model.entity.Job;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    Job selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB
     *
     * @mbg.generated Wed Apr 21 19:10:51 JST 2021
     */
    int updateByPrimaryKey(Job record);
}